language: ruby
cache: bundler

before_install:
  - mkdir -p $HOME/bin
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url http://095d8acfaaf71b4a0f3767e41152620ebdda1b31@mark.stridespace.com

install:
  - echo "install .."

env:
  matrix:
   - JOB=ABC
   - JOB=DEF
  
script:
  - echo "script .."
  - printenv > printenv.txt
 
after_script:
  - testspace ["Job $TRAVIS_JOB_NUMBER"]test.xml "+printenv.txt{environment variables}"
